# -*- coding: utf-8 -*-
"""Covid_slot_tracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q8Lh8iLJXv5xvfwADxQ6h6k9JorFXn64
"""

import time
import pytz
from datetime import datetime
IST = pytz.timezone('Asia/Kolkata')

import requests

def find_vaccines(pincode, date):
    URL = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode="+pincode+"&date="+date
    r = requests.get(url = URL, )
    if r.status_code==200:
        response = r.json()['centers']
        
        for each in response:
            for session in each['sessions']:
                if session['available_capacity_dose1'] and session['min_age_limit']==18:
                    
                    return session['available_capacity_dose1']
                    
        return 0
    return -1

def check(pincode, date):
  dose=find_vaccines(pincode, date)
  while(dose==0):
    print(datetime.now(IST).strftime('%I:%M:%S %p'))
    print("searching...")
    time.sleep(1.5)
    dose=find_vaccines(pincode, date)
  if (dose==-1):
    print("Try again")
  else:
    print("Mil gayi vaccine")
    print(dose)

pincode="452001"
date="03-06-2021"

check(pincode, date)
